version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.2

workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          package-manager: yarn
          cypress-cache-key: custom-cypress-cache-v1-{{ arch }}-{{ checksum "package.json" }}
          cypress-cache-path: ~/.cache/custom-dir/Cypress
          cypress-command: |
            if [ $CIRCLE_BRANCH == "main" ]
            then
                yarn cypress
            fi
                echo 'skipped e2e tests'
          node-cache-version: v2
